name: Create and publish documentation
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  documentation:
    runs-on: ubuntu-20.04
    name: Create the documentation and deploy it to GitHub Pages
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas markdown pytablereader tabulate
          npm install
      - name: Prepare tables
        run: |
          cd docs/devices
          python generate_devices_tables.py
      - name: Build documentation
        run: |
          npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          cname: decoder.theengs.io